language: csharp
solution: ./csharp/Common.sln
install:
  - nuget restore ./csharp/Common.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug ./csharp/travisci/Common.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./csharp/CommonTests/bin/Debug/CommonTests.dll
